#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
# robot_simple：几何已由 setup_robot.sh 放在 constant/triSurface/hull.stl

runApplication surfaceFeatureExtract

runApplication blockMesh

for i in $(seq 1 5)
do
    runApplication -s "$i" \
        topoSet -dict system/topoSetDict.${i}

    runApplication -s "$i" \
        refineMesh -dict system/refineMeshDict -overwrite
done

runApplication snappyHexMesh -overwrite

restore0Dir

runApplication setFields

runParallel -s decompose redistributePar -decompose

runParallel renumberMesh -overwrite

runParallel $(getApplication)

runParallel -s reconstruct redistributePar -reconstruct

#------------------------------------------------------------------------------
